name: Release Worflow Agenda

on:
  push:
    tags:
      - 'v*..'

jobs:
  build:
    name: Detectar nova versão
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Mostrar referência completa
        run: echo "Tag detectada:'$GITHUB_REF'"

      - name: Mostrar nome simplificado da tag
        run: echo "Versão publicada:${GITHUB_REF_NAME}"

      - name: Exemplo - gerar log da versão
        run: |
          echo "Nova versão lançada: ${GITHUB_REF_NAME}" > release_log.txt
          cat release_log.txt